package Model;
// Generated May 12, 2020 5:16:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bookcategory generated by hbm2java
 */
public class Bookcategory  implements java.io.Serializable {


     private int categoryId;
     private String categoryName;
     private Set books = new HashSet(0);

    public Bookcategory() {
    }

	
    public Bookcategory(int categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }
    public Bookcategory(int categoryId, String categoryName, Set books) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.books = books;
    }
   
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


