package Model;
// Generated May 12, 2020 5:16:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private int id;
     private Bookcategory bookcategory;
     private String title;
     private String publishingHouse;
     private Date publicationDate;
     private String author;
     private int pages;

    public Book() {
    }

    public Book(int id, Bookcategory bookcategory, String title, String publishingHouse, Date publicationDate, String author, int pages) {
       this.id = id;
       this.bookcategory = bookcategory;
       this.title = title;
       this.publishingHouse = publishingHouse;
       this.publicationDate = publicationDate;
       this.author = author;
       this.pages = pages;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Bookcategory getBookcategory() {
        return this.bookcategory;
    }
    
    public void setBookcategory(Bookcategory bookcategory) {
        this.bookcategory = bookcategory;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPublishingHouse() {
        return this.publishingHouse;
    }
    
    public void setPublishingHouse(String publishingHouse) {
        this.publishingHouse = publishingHouse;
    }
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public int getPages() {
        return this.pages;
    }
    
    public void setPages(int pages) {
        this.pages = pages;
    }




}


