package Model;
// Generated May 12, 2020 5:16:09 PM by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer regNo;
     private String firstName;
     private String lastName;
     private String phoneNo;
     private String email;
     private String category;
     private String photo;

    public Client() {
    }

    public Client(String firstName, String lastName, String phoneNo, String email, String category, String photo) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.phoneNo = phoneNo;
       this.email = email;
       this.category = category;
       this.photo = photo;
    }
   
    public Integer getRegNo() {
        return this.regNo;
    }
    
    public void setRegNo(Integer regNo) {
        this.regNo = regNo;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }




}


